// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("PassengerID");

                    b.HasIndex("TrainID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("dotnetapp.Models.Train", b =>
                {
                    b.Property<int>("TrainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainID"), 1L, 1);

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.HasKey("TrainID");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainID = 1,
                            DepartureLocation = "Location1",
                            DepartureTime = new DateTime(2024, 4, 26, 9, 18, 27, 314, DateTimeKind.Local).AddTicks(3957),
                            Destination = "Destination1",
                            MaximumCapacity = 4
                        },
                        new
                        {
                            TrainID = 2,
                            DepartureLocation = "Location2",
                            DepartureTime = new DateTime(2024, 4, 26, 9, 18, 27, 314, DateTimeKind.Local).AddTicks(3973),
                            Destination = "Destination2",
                            MaximumCapacity = 3
                        },
                        new
                        {
                            TrainID = 3,
                            DepartureLocation = "Location3",
                            DepartureTime = new DateTime(2024, 4, 26, 9, 18, 27, 314, DateTimeKind.Local).AddTicks(3974),
                            Destination = "Destination3",
                            MaximumCapacity = 2
                        },
                        new
                        {
                            TrainID = 4,
                            DepartureLocation = "Location4",
                            DepartureTime = new DateTime(2024, 4, 26, 9, 18, 27, 314, DateTimeKind.Local).AddTicks(3975),
                            Destination = "Destination4",
                            MaximumCapacity = 4
                        },
                        new
                        {
                            TrainID = 5,
                            DepartureLocation = "Location5",
                            DepartureTime = new DateTime(2024, 4, 26, 9, 18, 27, 314, DateTimeKind.Local).AddTicks(3976),
                            Destination = "Destination5",
                            MaximumCapacity = 3
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Passenger", b =>
                {
                    b.HasOne("dotnetapp.Models.Train", "Train")
                        .WithMany("Passengers")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("dotnetapp.Models.Train", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
