// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Passenger", b =>
                {
                    b.Property<int>("PassengerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainID")
                        .HasColumnType("int");

                    b.HasKey("PassengerID");

                    b.HasIndex("TrainID");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("dotnetapp.Models.Train", b =>
                {
                    b.Property<int>("TrainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainID"), 1L, 1);

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("int");

                    b.HasKey("TrainID");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainID = 1,
                            DepartureLocation = "Delhi",
                            DepartureTime = new DateTime(2024, 4, 27, 15, 16, 31, 349, DateTimeKind.Local).AddTicks(6829),
                            Destination = "Mumbai",
                            MaximumCapacity = 4
                        },
                        new
                        {
                            TrainID = 2,
                            DepartureLocation = "Chennai",
                            DepartureTime = new DateTime(2024, 4, 27, 16, 16, 31, 349, DateTimeKind.Local).AddTicks(6854),
                            Destination = "Kolkata",
                            MaximumCapacity = 3
                        },
                        new
                        {
                            TrainID = 3,
                            DepartureLocation = "Bangalore",
                            DepartureTime = new DateTime(2024, 4, 27, 22, 16, 31, 349, DateTimeKind.Local).AddTicks(6856),
                            Destination = "Hyderabad",
                            MaximumCapacity = 2
                        },
                        new
                        {
                            TrainID = 4,
                            DepartureLocation = "Jaipur",
                            DepartureTime = new DateTime(2024, 4, 27, 18, 16, 31, 349, DateTimeKind.Local).AddTicks(6857),
                            Destination = "Ahmedabad",
                            MaximumCapacity = 4
                        },
                        new
                        {
                            TrainID = 5,
                            DepartureLocation = "Lucknow",
                            DepartureTime = new DateTime(2024, 4, 27, 20, 16, 31, 349, DateTimeKind.Local).AddTicks(6858),
                            Destination = "Bhopal",
                            MaximumCapacity = 3
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Passenger", b =>
                {
                    b.HasOne("dotnetapp.Models.Train", "Train")
                        .WithMany("Passengers")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("dotnetapp.Models.Train", b =>
                {
                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
