// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240429042305_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"), 1L, 1);

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.Property<int?>("TurfID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("TurfID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("dotnetapp.Models.Turf", b =>
                {
                    b.Property<int>("TurfID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurfID"), 1L, 1);

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurfID");

                    b.ToTable("Turfs");

                    b.HasData(
                        new
                        {
                            TurfID = 1,
                            Availability = true,
                            Capacity = 4,
                            Name = "Turf A"
                        },
                        new
                        {
                            TurfID = 2,
                            Availability = true,
                            Capacity = 6,
                            Name = "Turf B"
                        },
                        new
                        {
                            TurfID = 3,
                            Availability = true,
                            Capacity = 2,
                            Name = "Turf C"
                        },
                        new
                        {
                            TurfID = 4,
                            Availability = false,
                            Capacity = 10,
                            Name = "Turf D"
                        },
                        new
                        {
                            TurfID = 5,
                            Availability = true,
                            Capacity = 2,
                            Name = "Turf E"
                        },
                        new
                        {
                            TurfID = 6,
                            Availability = false,
                            Capacity = 2,
                            Name = "Turf F"
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Booking", b =>
                {
                    b.HasOne("dotnetapp.Models.Turf", "Turf")
                        .WithMany("Bookings")
                        .HasForeignKey("TurfID");

                    b.Navigation("Turf");
                });

            modelBuilder.Entity("dotnetapp.Models.Turf", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
