// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnetapp.Models;

#nullable disable

namespace dotnetapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("dotnetapp.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"), 1L, 1);

                    b.Property<int>("DiningTableID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.HasKey("BookingID");

                    b.HasIndex("DiningTableID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("dotnetapp.Models.DiningTable", b =>
                {
                    b.Property<int>("DiningTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiningTableID"), 1L, 1);

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.HasKey("DiningTableID");

                    b.ToTable("DiningTables");

                    b.HasData(
                        new
                        {
                            DiningTableID = 1,
                            Availability = true,
                            SeatingCapacity = 4
                        },
                        new
                        {
                            DiningTableID = 2,
                            Availability = true,
                            SeatingCapacity = 6
                        },
                        new
                        {
                            DiningTableID = 3,
                            Availability = true,
                            SeatingCapacity = 2
                        },
                        new
                        {
                            DiningTableID = 4,
                            Availability = false,
                            SeatingCapacity = 10
                        },
                        new
                        {
                            DiningTableID = 5,
                            Availability = true,
                            SeatingCapacity = 2
                        },
                        new
                        {
                            DiningTableID = 6,
                            Availability = false,
                            SeatingCapacity = 2
                        });
                });

            modelBuilder.Entity("dotnetapp.Models.Booking", b =>
                {
                    b.HasOne("dotnetapp.Models.DiningTable", "DiningTable")
                        .WithMany("Bookings")
                        .HasForeignKey("DiningTableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningTable");
                });

            modelBuilder.Entity("dotnetapp.Models.DiningTable", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
