using NUnit.Framework;
using System;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using dotnetapp.Models;
using System.Reflection;

namespace dotnetapp.Tests
{
    [TestFixture]
    public class InventoryControllerTests
    {
         private const string InventoryServiceName = "InventoryService";
         private const string InventoryControllerName = "InventoryController";

        private HttpClient _httpClient;
        private Assembly _assembly;
        private InventoryItem _testInventoryItem;

        [SetUp]
        public async Task Setup()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = new Uri("http://localhost:8080"); // Base URL of your API
            _assembly = Assembly.GetAssembly(typeof(dotnetapp.Services.InventoryService));
            
            // Create a new test item before each test case
            _testInventoryItem = await CreateTestInventoryItem();
        }

        private async Task<InventoryItem> CreateTestInventoryItem()
        {
            var newInventoryItem = new InventoryItem
            {
                ItemId = 0, // Assuming ID will be generated by the server
                ItemName = "Test Item",
                Quantity = 10,
                Price = 9.99m,
                Category = "Test Category"
            };

            var json = JsonConvert.SerializeObject(newInventoryItem);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await _httpClient.PostAsync("api/inventory", content);
            response.EnsureSuccessStatusCode();

            return JsonConvert.DeserializeObject<InventoryItem>(await response.Content.ReadAsStringAsync());
        }

        [Test]
        public async Task Test_GetAllInventories_ReturnsListOfInventories()
        {
            // Arrange - no specific arrangement needed as we're not modifying state
            // Act
            var response = await _httpClient.GetAsync("api/Inventory");
            response.EnsureSuccessStatusCode();

            // Assert
            var content = await response.Content.ReadAsStringAsync();
            var items = JsonConvert.DeserializeObject<InventoryItem[]>(content);

            Assert.IsNotNull(items);
            Assert.IsTrue(items.Length > 0);
        }

        [Test]
        public async Task Test_GetInventoryById_ValidId_ReturnsItem()
        {
            // Arrange - no specific arrangement needed as we're not modifying state
            // Act
            var response = await _httpClient.GetAsync($"api/inventory/{_testInventoryItem.ItemId}");

            // Assert
            Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);

            var content = await response.Content.ReadAsStringAsync();
            var inventory = JsonConvert.DeserializeObject<InventoryItem>(content);

            Assert.IsNotNull(inventory);
            Assert.AreEqual(_testInventoryItem.ItemId, inventory.ItemId);
        }

        [Test]
        public async Task Test_GetInventoryById_ValidId_ReturnsItemTest_GetInventoryById_ValidId_ReturnsItem()
        {
            var response = await _httpClient.GetAsync("api/Inventory/999999"); // Using an invalid ID
            
            Assert.AreEqual(HttpStatusCode.NotFound, response.StatusCode);
        }

        [Test]
        public void Test_InventoryService_Exist()
        {
            AssertServiceInstanceNotNull(InventoryServiceName);
        }

        private void AssertServiceInstanceNotNull(string serviceName)
        {
            Type serviceType = _assembly.GetType($"dotnetapp.Services.{serviceName}");

            if (serviceType == null)
            {
                Assert.Fail($"Service {serviceName} does not exist.");
            }

            object serviceInstance = Activator.CreateInstance(serviceType);
            Assert.IsNotNull(serviceInstance);
        }
        [Test]
        public void Test_InventoryController_Exist()
        {
            AssertControllerClassExist(InventoryControllerName);
        }

        private void AssertControllerClassExist(string controllerName)
        {
            Type controllerType = _assembly.GetType($"dotnetapp.Controllers.{controllerName}");

            if (controllerType == null)
            {
                Assert.Fail($"Controller {controllerName} does not exist.");
            }
        }


        [TearDown]
        public async Task Cleanup()
        {
            _httpClient.Dispose();
        }

    }
}
