#!/bin/bash
export CHROME_BIN=/usr/bin/chromium
if [ ! -d "/home/coder/project/workspace/angularapp" ]
then
    cp -r /home/coder/project/workspace/karma/angularapp /home/coder/project/workspace/;
fi

if [ -d "/home/coder/project/workspace/angularapp" ]
then
    echo "project folder present"
    cp /home/coder/project/workspace/karma/karma.conf.js /home/coder/project/workspace/angularapp/karma.conf.js;
    # checking for tutor-form.component.spec.ts component
    if [ -d "/home/coder/project/workspace/angularapp/src/app/tutor-form" ]
    then
        cp /home/coder/project/workspace/karma/tutor-form.component.spec.ts /home/coder/project/workspace/angularapp/src/app/tutor-form/tutor-form.component.spec.ts;
    else
        echo "should_create_TutorFormComponent FAILED";
	echo "TutorFormComponent_should_render_error_messages_when_required_fields_are_empty_on_submit FAILED";
        echo "TutorFormComponent_should_call_add_tutor_method_while_adding_the_tutor FAILED";
    fi

    # checking for tutor-list.component.spec.ts component
    if [ -d "/home/coder/project/workspace/angularapp/src/app/tutor-list" ]
    then
        cp /home/coder/project/workspace/karma/tutor-list.component.spec.ts /home/coder/project/workspace/angularapp/src/app/tutor-list/tutor-list.component.spec.ts;
    else
        echo "should_create_tutor_listComponent FAILED";
        echo "tutor_listComponent_should_call_loadTutors_on_ngOnInit FAILED";
    fi

    # checking for tutor.model.spec.ts component
    if [ -e "/home/coder/project/workspace/angularapp/src/app/models/tutor.model.ts" ]
    then
        cp /home/coder/project/workspace/karma/tutor.model.spec.ts /home/coder/project/workspace/angularapp/src/app/models/tutor.model.spec.ts;
    else
        echo "Models_should_create_tutor_instance FAILED";
    fi

    # checking for app.component.spec.ts component
    if [ -d "/home/coder/project/workspace/angularapp/src/app/delete-confirm" ]
    then
        cp /home/coder/project/workspace/karma/delete-confirm.component.spec.ts /home/coder/project/workspace/angularapp/src/app/delete-confirm/delete-confirm.component.spec.ts;
    else
        echo "should_create_DeleteConfirmComponent FAILED";
	echo "DeleteConfirmComponent_should_call_deleteTutor_method_when_confirmDelete_is_called FAILED";
    fi

    # checking for header.component.spec.ts component
    if [ -e "/home/coder/project/workspace/angularapp/src/app/header" ]
    then
        cp /home/coder/project/workspace/karma/header.component.spec.ts /home/coder/project/workspace/angularapp/src/app/header/header.component.spec.ts;
    else
        echo "should_create_HeaderComponent FAILED";
    fi

    # checking for tutor.service.spec.ts component
    if [ -e "/home/coder/project/workspace/angularapp/src/app/services/tutor.service.ts" ]
    then
        cp /home/coder/project/workspace/karma/tutor.service.spec.ts /home/coder/project/workspace/angularapp/src/app/services/tutor.service.spec.ts;
    else
        
        echo "TutorService_should_be_created FAILED";
        echo "TutorService_should_add_a_tutor_and_return_it FAILED";
        echo "TutorService_should_get_tutors FAILED";
        echo "TutorService_should_delete_tutor FAILED";
        echo "TutorService_should_get_tutor_by_id FAILED";
    fi

    if [ -d "/home/coder/project/workspace/angularapp/node_modules" ];
    then
        cd /home/coder/project/workspace/angularapp/
        npm test;
    else
        cd /home/coder/project/workspace/angularapp/
        yes | npm install
        npm test
    fi 
else   
        echo "should_create_TutorFormComponent FAILED";
        echo "RecipeFormComponent_should_not_render_any_error_messages_when_all_fields_are_filled FAILED";
        echo "RecipeFormComponent_should_call_add_tutor_method_while_adding_the_tutor FAILED";
        echo "should_create_tutor_listComponent FAILED";
        echo "tutor_listComponent_should_call_loadRecipes_on_ngOnInit FAILED";
        echo "Models_should_create_tutor_instance FAILED";
        echo "should_create_DeleteConfirmComponent FAILED";
        echo "DeleteConfirmComponent_should_call_deleteRecipe_method_when_confirmDelete_is_called FAILED";
        echo "should_create_HeaderComponent FAILED";
        echo "RecipeService_should_be_created FAILED";
        echo "RecipeService_should_add_a_tutor_and_return_it FAILED";
        echo "RecipeService_should_get_tutors FAILED";
        echo "RecipeService_should_delete_tutor FAILED";
        echo "RecipeService_should_get_tutor_by_id FAILED";
fi
