// add-course.component.ts
import { Component } from '@angular/core';
import { Course } from 'src/app/models/course.model';
import { CourseService } from 'src/app/services/course.service';


@Component({
  selector: 'app-add-course',
  templateUrl: './add-course.component.html',
  styleUrls: ['./add-course.component.css']
})
export class AddCourseComponent {

  newCourse: Course = {
    courseID: 0, // This will be generated by the server
    courseName: '',
    description: '',
    duration: '',
    amount: 0
  };

  constructor(private courseService: CourseService) { }

  addCourse(): void {
    this.courseService.createCourse(this.newCourse).subscribe(() => {
      // Handle successful creation, e.g., show a success message or navigate to another page
    });
  }
}
